// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner.vue')['default']
    BaseInfo: typeof import('./components/dataComponents/BaseInfo.vue')['default']
    ComTabs: typeof import('./components/ComTabs.vue')['default']
    ComTabsCard: typeof import('./components/ComTabsCard.vue')['default']
    DataDetails: typeof import('./components/DataDetails.vue')['default']
    DataTable: typeof import('./components/dataComponents/DataTable.vue')['default']
    DetailBanner: typeof import('./components/DetailBanner.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlobalSearchWrap: typeof import('./components/layout/components/GlobalSearchWrap.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Login: typeof import('./components/login/index.vue')['default']
    Menu: typeof import('./components/layout/Menu.vue')['default']
    MetaData: typeof import('./components/dataComponents/MetaData.vue')['default']
    PartyInfo: typeof import('./components/commonTable/PartyInfo.vue')['default']
    PersonalCenter: typeof import('./components/layout/components/PersonalCenter.vue')['default']
    PersonalDrawer: typeof import('./components/layout/components/PersonalDrawer.vue')['default']
    PersonalPopover: typeof import('./components/layout/components/PersonalPopover.vue')['default']
    QuestionMark: typeof import('./components/QuestionMark.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    Side: typeof import('./components/layout/Side.vue')['default']
    TaskInvolved: typeof import('./components/dataComponents/TaskInvolved.vue')['default']
    TaskParamsTransfer: typeof import('./components/TaskParamsTransfer.vue')['default']
  }
}

export { }
